name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - live
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CMSPracticalShooterApp/fire-cms
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Adjust this to your project's Node.js version
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Select Firebase Alias
        run: firebase use default
      - name: Deploy to Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
