name: Deploy to Firebase Hosting on push to live

on:
  push:
    branches:
      - live

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CMSPracticalShooterApp/fire-cms
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20' # Make sure this matches your project requirements

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: yarn build # Or your custom build script, if different

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
