name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - live
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CMSPracticalShooterApp/fire-cms
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify your Node.js version here
      - name: Install Dependencies
        run: yarn install
      - name: Build and Deploy
        run: yarn build && firebase deploy
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_THE_PRACTICAL_SHOOTER_APP }}'
          channelId: live
          projectId: the-practical-shooter-app
